development:
  database: buzzer_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pgadmin
  password: pgadmin
  host: localhost
  port: 5432

test:
  database: buzzer_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pgadmin
  password: pgadmin
  host: localhost
  port: 5432